### ISSUE TITLE
Seems conflict with Image Browser

### ISSUE THREAD

**Issue by SLAPaper** [ilian6806/stable-diffusion-webui-state#12]
Image Browser: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser

state version: 50ff7bb3 (Thu Mar 30 13:11:50 2023)
image browser version: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/commit/df3d541307ff59e06a9de982be25c5f12d5b6d9c (Thu Mar 30 12:50:02 2023)

Enable state causing Image browser lose the ability to show full UI & show image metadata:

Disable State:
![image](https://user-images.githubusercontent.com/7543632/228928099-10dd65b8-9efa-48dc-9c52-b5e6c2d45165.png)

Enable State:
![image](https://user-images.githubusercontent.com/7543632/228928299-3319f301-7db0-4573-b55e-94f22e759a68.png)

There is no relevant output in console.

**Comment by ilian6806** [comment]
Fixed with [https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/110](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/110)
