### ISSUE TITLE
Change "Reset" Button

### ISSUE THREAD

**Issue by ParityError** [ilian6806/stable-diffusion-webui-state#16]
Hello,

Great extension! It's incredibly useful, and I'm surprised that the webui doesn't include this functionality by default. 

I have one suggestion, and that's about the emoji that you use for the reset back to default. The current one is very similar to the refresh models emoji `🔄` right next to it and could easily be confused. I changed it to `*️⃣` and it seems to be a good fit. I chose the asterisk simply because it's the same in style to the refresh models emoji and it implies "return" and "all" in some regards. 

```
 resetBtn.innerHTML = "*️⃣";
```

**Comment by ilian6806** [comment]
Done. I will include this in the next release soon. I also made some changes to fit the look of the latest SD and gradio. I dont know how this would look in oldest versions.
