### ISSUE TITLE
Issue with ControlNet

### ISSUE THREAD

**Issue by davehornik** [ilian6806/stable-diffusion-webui-state#20]
Hey!
_I guess_ it's not an issue of this extension.
But something going on with ControlNet extension enabled with yours also.
Maybe you can tell me why [THIS](https://github.com/Mikubill/sd-webui-controlnet/issues/721#issuecomment-1501234262) is an issue, or bring some light to it, bcuz I am clueless what to do since I need/like both extensions.

**Comment by ilian6806** [comment]
I cant reproduce this with latest versions of SD, ControlNet and Image browser... Is there some message in the browser console (JS) ?
