### ISSUE TITLE
Doesn't save Scale by/Scale to information.

### ISSUE THREAD

**Issue by brknsoul** [ilian6806/stable-diffusion-webui-state#23]
It'd be nice (if possible) if this could (optionally?) save Scale by/to sliders and Upscaler method.

**Comment by ilian6806** [comment]
This inputs must be saved like all the others. Is something not working for you?

**Comment by brknsoul** [comment]
Typically Post-process upscaling is done in the Extras tab, but you can add it to the txt2img tab (via Settings) and have it auto-run immediately after generating an image. This extension doesn't seem to recognise this.

My go-to settings;
![image](https://user-images.githubusercontent.com/1969381/232631062-a0b0c6dd-2710-484c-9e97-9ac2f1c1a81a.png)

Upscale state test before;
![image](https://user-images.githubusercontent.com/1969381/232631158-ea769966-8c80-4ffa-9ce7-598c8d9ac40a.png)

Upscale state test after;
![image](https://user-images.githubusercontent.com/1969381/232631231-e990f68e-9b02-444a-a715-025ff47df805.png)

Notice the Upscale settings haven't saved.

Note that these _aren't_ the Hires Fix settings.

**Comment by ilian6806** [comment]
I see. I checked this and unfortunatelly these elements have same ids in txt2img and img2img. I will be able to do this only after (if) this is fixed in Web UI.

**Comment by ilian6806** [comment]
Fixed in last update. State is the same for txt2img and img2img since the elements still share the same ids.
