### ISSUE TITLE
Settings not saving on mobile?

### ISSUE THREAD

**Issue by annasophiachristianahahn** [ilian6806/stable-diffusion-webui-state#25]
Hello!

I am running colab automatic1111 from a windows machine but accessing the gradio interface on iOS 

I can’t seem to get the extension to recall settings after reload even though I have all of the boxes checked in the State extension settings 

what else do I need to do to make it work properly?

thank you very much!

**Comment by ilian6806** [comment]
Sorry but I currently dont have iOS device to test it. I suppose it is one of the many iOS web issues. If you try it on safari may be you can try chrome...
