### ISSUE TITLE
This works， perfectly， Thanks ilian6806

### ISSUE THREAD

**Issue by LanceGao97** [ilian6806/stable-diffusion-webui-state#26]
This works， perfectly， Thanks ilian6806
everyproject can be saved now, 

this is very useful when handling complex image project,  when GPU out of memory ， everything bugs and image is strange,
restart with this code, and it works.

**Comment by LanceGao97** [comment]
also， it's don't save controlnet  images and controle net settings, but it's already good enough.

**Comment by ilian6806** [comment]
Hi! Images will be a tricky one but I will give it a try when I find the time. Thanks for your feedback. You can use Discussions tab if you have any other ideas!
