### ISSUE TITLE
Support for extension

### ISSUE THREAD

**Issue by PotatoBananaApple** [ilian6806/stable-diffusion-webui-state#29]
Hey, would it be possible to add support to save settings for extension: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 ? It has quite few settings and makes annoying to reload ui :)

**Comment by ilian6806** [comment]
Unfortunately, in order to add some elements to memory, they must have some id`s in the markup. So to support some extension, the author must do this before I can memorize it. You can create an issue in their repo for this. This will not take much time.

**Comment by chuckkay** [comment]
specifically want ControlNet v1.1.200batch input directory location, but also these arent saved on restart
Enable
Low VRAM
Pixel Perfect
Allow Preview
Control Type
