### ISSUE TITLE
"Show/hide extra networks" button not working

### ISSUE THREAD

**Issue by Quidam2k** [ilian6806/stable-diffusion-webui-state#35]
When I disable this extension and reload, it does. Would sometimes work out of the blue, then stop working again.

**Comment by KominoStyle** [comment]
I think there might be a conflict with another extension. If you can identify the extension causing the conflict, it would greatly assist in troubleshooting and finding a solution. I've encountered a similar situation before. But never had the problem with the networks button.

**Comment by DrMacabre** [comment]
got the same problem, it's one of these extensions 
![image](https://github.com/ilian6806/stable-diffusion-webui-state/assets/49474452/aef43f6d-b83c-404a-922c-413a09c2ae18)

**Comment by crowbait** [comment]
This is related: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10304

**Comment by ilian6806** [comment]
https://www.reddit.com/r/StableDiffusion/comments/16ngxab/showhidden_extra_networks_does_not_appear/

I think this is irrelevant now.
