### ISSUE TITLE
Enabling extension appears to break the Scripts menu on img2img

### ISSUE THREAD

**Issue by tensiondriven** [ilian6806/stable-diffusion-webui-state#39]
Hola,

I love this extension.

On my install, when I enable the extension and go to the img2img tab, the "Scripts" drop-down does not show content.  I can change it, but after changing, the script is not loaded.

Is this a known issue?  If not, could this be corrupt state?   Could the extension be improved to be more resilient to such conditions?

**Comment by tensiondriven** [comment]
Well how about that, disabling "Script" in the Settings fixes this issue for me.  I don't get to have persistent state for img2img script, but that's fine.  I'll leave this open in case you think there's a way to improve error handling / edge cases like this, but as far as I'm concerned, this issue can be closed.

**Comment by ilian6806** [comment]
I can't reproduce this with the latest version of web UI. I suppose it was caused by another extension/script.
