### ISSUE TITLE
Reset to default button on each state

### ISSUE THREAD

**Issue by Auvere** [ilian6806/stable-diffusion-webui-state#4]
A button to reset to default (to simply delete the key in local storage) would be interesting so it then reads ui-config.json again instead. And maybe even an option to overwrite the values in ui-config.json as a way to store the state "permanently"

**Comment by BWDrum** [comment]
Two requests, please...

1. Would love a "select all" button on your settings page, or even better...  "select all except seed" 
2.  Add ControlNet save settings... that would get you a donation! 
3. Thank you for this awesome extension, I was hoping someone would create something like this, it's very useful.

**Comment by ilian6806** [comment]
I just added a simple button for reseting the state next to the checkpoint dropdown. I am planning to add separate deleting of all state variables. ControlNet support will be a bit more trickier and time consuming since most of the elements dont have id`s and the things are changing every day, but I will see what I can do :)

**Comment by ilian6806** [comment]
I just merged the PR with control net support. Let me know if you find some bugs :)

**Comment by ilian6806** [comment]
I added 'Select All', 'Select All Except Seeds' and 'Unselect All' buttons  in settings page.

**Comment by BWDrum** [comment]
Hello,

Unfortunately, these new features are not showing up or working for me. Over the last few days State wasn't working at all but I know how updates work. When Auto 1111 updates I need to be patient with extension developers. 

Now State is working as before, including the "reset state next to the checkpoint dropdown" but State will not remember the ControlNet settings nor do I see the new options to "Select All..." 

I have updated, shut everything down, rebooted, relaunched and updated again (a few times) but no luck. 

Thank you for your efforts on this, I find it be a valuable addition to my workflow. 

Cheers

**Comment by ilian6806** [comment]
I updated my SD version to latest and there were A LOT of changes there.
- gradio version was updated
- selects is not native html elements anymore, but custom ones
- get_uiCUrrentTab method does not work anymore
- onUiTabChange callback not working properly at the moment
- changed css classes almost everywhere
So yes, as this is almost entirely JS extension, it depends on some html structure when there is no id attributes there and it is very fragile and hard to support.

Today I fixed most of this issues and found some new ones... I also applied your fixes. You can update the extension and check if its working for you. If not, please check js console for errors, to give me a hint for eventual problems.

Cheers :)

**Comment by Tynk3r** [comment]
hey ilian, first of all thank you for the amazing idea and extension. works really well and i (and many others, im sure) are very grateful for this tool. could i suggest the ability to save inpainting option states as well (masked content, inpaint area etc)? Thank you!
