### ISSUE TITLE
Save state for Postprocess which is not included

### ISSUE THREAD

**Issue by FutonGama** [ilian6806/stable-diffusion-webui-state#41]
For people who don't know here is a trick, you can add the extra tab directly on txt2img tab for generate and will auto upscale after. But state extension don't save this settings and need to put the config everytime we reload the page which is very annoying, if you guys can add that for be saved i will appreciate alot. 

For add that extra in txt2img go to your SD webui settings, go to postprocess tab and add Upscale to boths lines. Also you can add other things from extra like face restoration methods and other extensions options if you have.
![post processs](https://github.com/ilian6806/stable-diffusion-webui-state/assets/95169493/edcf0a7b-e5fe-4b34-9929-82ee4ecec283)

This is the configuration who needs to be saved with state. (I'm using Lobe UI but is not related to the UI)
![Postprocess](https://github.com/ilian6806/stable-diffusion-webui-state/assets/95169493/20ab83e1-be82-44c3-a08b-0420571668b9)

People not usually knows about add extras to txt2img so i have teach it here, i hope they discover, i hope also you guys make it possible to be saved with state. (I know this is not a issue, its a request, i tried to add on Pull requests but i don't find a way to do that idk why). Thank You for the excellent work! Cheers!

**Comment by ilian6806** [comment]
Thanks for the feedback! In the future, you can use the discussion tab for any proposals :) I will check this if I find free time. Cheers!

**Comment by ilian6806** [comment]
In the latest version of state extension, I have added exactly these params. :)
