### ISSUE TITLE
Issue with ControlNet v1.1.234 and FaceSwapLab v1.2.0

### ISSUE THREAD

**Issue by Yaiol** [ilian6806/stable-diffusion-webui-state#49]
When using SD webui with ControlNet v1.1.234 and FaceSwapLab v1.2.0 

https://github.com/glucauze/sd-webui-faceswaplab
https://github.com/Mikubill/sd-webui-controlnet

The Preprocessor and Model list are loading endless.

No idea if this is an issue with ControlNet, FaceSwapLab or with Stable-Diffusion-Webui-State, but it does **happen only when the three are used** together.

This didn't happen with previous versions
This does happen only Into txt2img tab, oddy this issue is not affecting img2img tab

![sd-webui-state-bug](https://github.com/ilian6806/stable-diffusion-webui-state/assets/38218161/85958548-c2bb-4184-a8d7-7771dab46e30)

**Comment by ilian6806** [comment]
Probably this is some conflict with other extension. If this is still an issue, can you check your browser console  for errors and share it here.
