### ISSUE TITLE
Stopped working for dev branch of auto111

### ISSUE THREAD

**Issue by sashasubbbb** [ilian6806/stable-diffusion-webui-state#50]
I’m not sure what’s changed, but this extension doesn’t seem to work for dev branch.
![8A88F51A-E998-4A8B-AFD3-D4D67472DF13](https://github.com/ilian6806/stable-diffusion-webui-state/assets/60400449/25274870-f0e0-47a8-b97a-7a1faf0894e8)

**Comment by ilian6806** [comment]
Hi, guys! Is this still happening? I usually worked with master branch, but I can`t reproduce this in even on dev...

**Comment by ilian6806** [comment]
Seems ok with the latest master branch.
