### ISSUE TITLE
Not (fully?) working with ControlNet and MultiDiffusion

### ISSUE THREAD

**Issue by mr-september** [ilian6806/stable-diffusion-webui-state#52]
I see they are supported and I have them enabled, 

![image](https://github.com/ilian6806/stable-diffusion-webui-state/assets/45350177/ad592edd-6d93-4357-983e-3d4d2c85eb79)

But it doesn't seem to be doing anything? Extension settings reset back to default every time I run/restart the webui.

**Comment by e2heintz** [comment]
For me it is teh same - controlnet settings are not saved.

**Comment by ilian6806** [comment]
Finally got it working with latest version...
