### ISSUE TITLE
No longer saves the latest interface elements of A1111 

### ISSUE THREAD

**Issue by yaronelh** [ilian6806/stable-diffusion-webui-state#53]
There is some new elements in the interface relating to XL models like the refiner and it's settings
probably because they are newer than the latest released version they're not getting saved

**Comment by arafatx** [comment]
Yes, this plugin is broken. I thought it was issue with other plugins. disabled all other plugins except this and it won't save.

**Comment by ilian6806** [comment]
I will try to add it as soon as I can, guys. I have no time to continuously update the plugin with all the changes. I was hoping for more contributors...

**Comment by ilian6806** [comment]
I`ve added refiner settings in the last update.
