### ISSUE TITLE
Demo Video not accessible, if using ad-blocker on Youtube

### ISSUE THREAD

**Issue by schoenid** [ilian6806/stable-diffusion-webui-state#54]
Youtube has blocked the access completely for me, because I don't want ads.
I think it is time, to search a different place, where videos can be stored without restrictions.

**Comment by ilian6806** [comment]
Try Opera for Youtube :)

На ср, 25.10.2023 г., 00:16 ч. Daniel Schöni ***@***.***>
написа:

**Comment by ilian6806** [comment]
This is really strange... However, I upload them in a cloud, so you can  watch them [here](https://u.pcloud.link/publink/show?code=kZ6F4oVZwzrQT5htSsQKB6XfB8nRth0STT6X).
