### ISSUE TITLE
Hires fix not enabled

### ISSUE THREAD

**Issue by Quidam2k** [ilian6806/stable-diffusion-webui-state#55]
Although the settings of the upscale section are restored, if I don't click to open the section, they won't be applied.

**Comment by Quidam2k** [comment]
The UI has changed so that there's a checkbox indicating hires fix is enabled, no longer relying on the section being expanded to indicate that. Hoped that it might mean the state got saved, but alas, still not saved.

**Comment by VL4DST3R** [comment]
+1 Came for the same reason. Have you found any replacement for this extension? as it seems to be abandoned.

**Comment by ilian6806** [comment]
Fixed in last [update](https://github.com/ilian6806/stable-diffusion-webui-state/pull/65). I also added refiner state. :)
