### ISSUE TITLE
Doesn't save Latent Couple state data

### ISSUE THREAD

**Issue by ice-fly** [ilian6806/stable-diffusion-webui-state#58]
Doesn't save the numeric/enabled state data for the [Latent Couple extension](https://github.com/ashen-sensored/stable-diffusion-webui-two-shot)
Might be an issue on their side.

**Comment by ilian6806** [comment]
No, extensions require additional work and support, unfortunately...

**Comment by ice-fly** [comment]
I've move over to https://github.com/SenshiSentou/sd-webui-state-manager for now...
It partially captuires that extension's state. Perhaps it would be worth combining efforts?
Thanks for your hard work though!
