### ISSUE TITLE
Support for multiple setups

### ISSUE THREAD

**Issue by TeKett** [ilian6806/stable-diffusion-webui-state#59]
When using multiple setups, if the extension is installed on both then both remembers the same settings, likely since the plugin stores the info globally on the system. I have a 1.5 setup and a XL setup since they need different settings. Any prompting i do for 1.5 gets loaded up when i run XL. Its a mild inconvenience, but an inconvenience nonetheless.

**Comment by DerHary** [comment]
Same here - for other things i do a Symlink switch, but i dont know where this extension saves its state Data

**Comment by ilian6806** [comment]
It uses local storage of the browser, so the state is stored by {domain}:{port}. You can run different setups in different port to separate the state.
