### ISSUE TITLE
Using this extension makes my hires fix options disappear

### ISSUE THREAD

**Issue by Powermonkey00** [ilian6806/stable-diffusion-webui-state#7]
Works great otherwise, but my hires fix options disappear when the extension is enabled.  Disabling the extension causes them to re-appear.

**Comment by Soulreaver90** [comment]
I don't have this issue. Are you running any other extensions by any chance?

**Comment by ilian6806** [comment]
I can't reproduce it too, but it got to be some collision with other extension.

**Comment by DrMacabre** [comment]
Happens to me too, had to revert to an older A1111.

**Comment by ilian6806** [comment]
Yesterday I made some changes  that fix multiple bugs with latest version og SD and gradio. Can you try it now?

**Comment by DrMacabre** [comment]
I tried this morning before reverting. It's still gone.
![image](https://user-images.githubusercontent.com/49474452/229361854-460b4b55-5fda-4225-ac21-65f974023547.png)

**Comment by ilian6806** [comment]
Is this the latest versions of SD and the extension?

**Comment by DrMacabre** [comment]
Yes, i did a git pull on both the extension and a1111 before capture.

**Comment by ilian6806** [comment]
I still cant reproduce this on latest versions :( Is there some error in the browser console?

**Comment by DrMacabre** [comment]
Sorry, im back on Commit hash: a9eab236d7e8afa4d6205127904a385b2c43bb24 for A1111, the latest is too broken for my usage.

**Comment by DrMacabre** [comment]
Hello, i made 2 seperate folder just to keep my old working version, now trying commit 22bcc of A1111 with commit 4cc8fa3c of your extension, hire.fix still doesn't open. No error in the console.
