### ISSUE TITLE
Most of the selected settings are not saved

### ISSUE THREAD

**Issue by Shyryp** [ilian6806/stable-diffusion-webui-state#72]
What I did:
I selected "Save all" data in the settings, rebooted Automatic1111 and tried exporting the changes.

As it turns out, only the following settings are saved:
{
     "state-img2img_checkpoint": "",
     "state-img2img_#script_list": "None",
     "state-img2img_sampling": "DPM++ 3M SDE",
     "state-img2img_seed": "-1",
     "state-img2img_styles": "",
     "state-img2img_scheduler": "Karras",
     "state-tab": "img2img",
     "state-img2img_prompt": "masterpiece, best quality, highres, <lora:more_details:0.5> <lora:SDXLrender_v2.0:1>,"
}

The plugin does NOT save other changed settings and fields.
That is, they are not saved:
- Negative prompt
- Checkpoint
- most img2img settings
- Controlnet
- Tile Diffusion
- Previously selected tabs are not selected (for example, Batch in img2img does not open on its own).

As a result, at the moment (with the latest updates for Automatic1111 (08 May 2024)) this plugin does NOT work almost completely.

**Comment by ilian6806** [comment]
Hi, @Shyryp ! Did you hit 'Apply settings' button before reloading the UI?

**Comment by EmoryAhlberg** [comment]
He's right, I'm afraid it's not working at all now.

**Comment by ilian6806** [comment]
I have made some fixes for the new Gradio. Unfortunately, the core code is constantly changing, and I can`t keep up with updating the extension. Please check your browser console if something isn`t working and share any errors you see.
